require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Product = require('../models/Product');

const sampleProducts = [
  {
    name: 'Classic Cotton T-Shirt',
    description: 'Soft and breathable cotton t-shirt for daily wear. Comfortable fit for all-day use.',
    price: 15.50,
    originalPrice: 25.00,
    discount: '38%',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80',
    category: "Men's",
    subcategory: 'Shirts',
    rating: 4.5,
    numReviews: 89,
    sold: 156,
    stock: 50,
    featured: true,
    isNew: false,
  },
  {
    name: 'Denim Jacket Blue',
    description: 'Premium blue denim jacket with modern fit and durable stitching. Perfect for casual outings.',
    price: 65.00,
    originalPrice: 95.00,
    discount: '32%',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&q=80',
    category: "Men's",
    subcategory: 'Jackets',
    rating: 4.8,
    numReviews: 134,
    sold: 234,
    stock: 30,
    featured: true,
    isNew: false,
  },
  {
    name: 'Black Leather Boots',
    description: 'Comfortable and stylish leather boots for all-day confidence. Water-resistant sole.',
    price: 89.99,
    originalPrice: 120.00,
    discount: '25%',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
    category: 'Footwear',
    subcategory: 'Boots',
    rating: 4.6,
    numReviews: 67,
    sold: 189,
    stock: 20,
    featured: false,
    isNew: false,
  },
  {
    name: 'Summer Dress Floral',
    description: 'Lightweight floral dress perfect for summer outings. Made with breathable fabric.',
    price: 42.00,
    originalPrice: 65.00,
    discount: '35%',
    image: 'https://images.unsplash.com/photo-1495385794356-15371f348c31?w=400&q=80',
    category: "Women's",
    subcategory: 'Dresses',
    rating: 4.7,
    numReviews: 212,
    sold: 312,
    stock: 45,
    featured: true,
    isNew: false,
  },
  {
    name: 'Winter Leather Jacket',
    description: 'Warm winter jacket designed for comfort and cold weather protection. Premium leather finish.',
    price: 89.00,
    originalPrice: 120.00,
    discount: '25%',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80',
    category: "Men's",
    subcategory: 'Jackets',
    rating: 4.5,
    numReviews: 55,
    sold: 120,
    stock: 15,
    featured: false,
    isNew: true,
  },
  {
    name: 'Camel Wool Coat',
    description: 'Elegant wool coat with a timeless silhouette and premium fabric. Great for winter styling.',
    price: 145.00,
    originalPrice: 200.00,
    discount: '27%',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400&q=80',
    category: "Women's",
    subcategory: 'Coats',
    rating: 4.6,
    numReviews: 42,
    sold: 96,
    stock: 12,
    featured: false,
    isNew: true,
  },
  {
    name: 'Black Leather Blazer',
    description: 'Sophisticated leather blazer for formal and casual styling. Versatile wardrobe staple.',
    price: 125.00,
    originalPrice: 180.00,
    discount: '30%',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&q=80',
    category: 'Outerwear',
    subcategory: 'Blazers',
    rating: 4.7,
    numReviews: 38,
    sold: 88,
    stock: 10,
    featured: false,
    isNew: true,
  },
  {
    name: 'Navy Blue Dress Shirt',
    description: 'Classic navy shirt with clean tailoring for office and events. Wrinkle-resistant fabric.',
    price: 65.00,
    originalPrice: 95.00,
    discount: '31%',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80',
    category: "Men's",
    subcategory: 'Shirts',
    rating: 4.4,
    numReviews: 76,
    sold: 140,
    stock: 35,
    featured: false,
    isNew: true,
  },
  {
    name: 'Gold Hoop Earrings',
    description: 'Classic gold hoop earrings that pair beautifully with any outfit. Hypoallergenic material.',
    price: 28.00,
    originalPrice: 45.00,
    discount: '37%',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&q=80',
    category: 'Jewelry',
    subcategory: 'Earrings',
    rating: 4.9,
    numReviews: 189,
    sold: 402,
    stock: 80,
    featured: true,
    isNew: false,
  },
  {
    name: 'Leather Crossbody Bag',
    description: 'Compact and stylish crossbody bag in genuine leather. Multiple compartments for organization.',
    price: 78.00,
    originalPrice: 110.00,
    discount: '29%',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80',
    category: 'Accessories',
    subcategory: 'Bags',
    rating: 4.6,
    numReviews: 94,
    sold: 178,
    stock: 25,
    featured: true,
    isNew: false,
  },
  {
    name: 'White Running Sneakers',
    description: 'Lightweight and comfortable sneakers designed for running and everyday use. Breathable mesh upper.',
    price: 55.00,
    originalPrice: 80.00,
    discount: '31%',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
    category: 'Footwear',
    subcategory: 'Sneakers',
    rating: 4.5,
    numReviews: 143,
    sold: 267,
    stock: 60,
    featured: false,
    isNew: true,
  },
  {
    name: 'Floral Silk Scarf',
    description: 'Elegant silk scarf with floral print. Can be worn in multiple ways.',
    price: 35.00,
    originalPrice: 55.00,
    discount: '36%',
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&q=80',
    category: 'Accessories',
    subcategory: 'Scarves',
    rating: 4.3,
    numReviews: 51,
    sold: 95,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Rose Gold Necklace',
    description: 'Delicate rose gold necklace with a minimalist pendant. Perfect gift for loved ones.',
    price: 48.00,
    originalPrice: 75.00,
    discount: '36%',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80',
    category: 'Jewelry',
    subcategory: 'Necklaces',
    rating: 4.8,
    numReviews: 107,
    sold: 231,
    stock: 55,
    featured: true,
    isNew: false,
  },
  {
    name: "Women's Yoga Pants",
    description: 'High-waisted yoga pants with four-way stretch fabric. Moisture-wicking and comfortable.',
    price: 38.00,
    originalPrice: 60.00,
    discount: '36%',
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&q=80',
    category: "Women's",
    subcategory: 'Activewear',
    rating: 4.7,
    numReviews: 298,
    sold: 540,
    stock: 75,
    featured: true,
    isNew: false,
  },
  {
    name: 'Slim Fit Chino Pants',
    description: 'Versatile slim fit chinos that work for both casual and semi-formal occasions.',
    price: 48.00,
    originalPrice: 70.00,
    discount: '31%',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80',
    category: "Men's",
    subcategory: 'Pants',
    rating: 4.4,
    numReviews: 88,
    sold: 195,
    stock: 45,
    featured: false,
    isNew: false,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB connected');

    await Product.deleteMany({});
    console.log('🗑️  Cleared existing products');

    const inserted = await Product.insertMany(sampleProducts);
    console.log(`✅ Seeded ${inserted.length} products`);

    await mongoose.disconnect();
    console.log('✅ Done. Database disconnected.');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
};

seedDB();
