require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
const Product = require('../models/Product');

const productsData = [
  // ==========================================
  // 1. GROCERY (15 Products)
  // ==========================================
  {
    name: 'Premium Basmati Rice – 5kg',
    description: 'Aged extra-long grain basmati rice. Fluffy, aromatic, and perfect for biryanis, pulao, and daily meals.',
    brand: 'Fortune',
    keywords: ['rice', 'basmati', 'grains', 'biryani', 'grocery', 'fortune'],
    price: 599,
    originalPrice: 799,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Rice & Grains',
    rating: 4.8,
    numReviews: 240,
    sold: 1850,
    stock: 120,
    featured: true,
    isNew: false,
  },
  {
    name: 'Cold-Pressed Virgin Olive Oil – 1L',
    description: '100% pure cold-pressed extra virgin olive oil from Mediterranean olives. Rich in antioxidants and healthy fats.',
    brand: 'Figaro',
    keywords: ['olive oil', 'cooking oil', 'virgin', 'healthy', 'grocery', 'figaro'],
    price: 899,
    originalPrice: 1199,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Oils & Ghee',
    rating: 4.7,
    numReviews: 180,
    sold: 940,
    stock: 85,
    featured: false,
    isNew: false,
  },
  {
    name: 'Organic White Quinoa Grain – 1kg',
    description: 'Certified gluten-free organic royal quinoa. High in protein, essential amino acids, and dietary fiber.',
    brand: 'Organic India',
    keywords: ['quinoa', 'organic', 'superfood', 'grain', 'healthy', 'protein'],
    price: 499,
    originalPrice: 649,
    discount: '23% OFF',
    image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Rice & Grains',
    rating: 4.6,
    numReviews: 115,
    sold: 520,
    stock: 90,
    featured: false,
    isNew: true,
  },
  {
    name: 'Pure Desi Cow Ghee – 1L',
    description: 'Traditional bilona churned pure cow ghee with a granular texture and golden aromatic essence.',
    brand: 'Amul',
    keywords: ['ghee', 'cow ghee', 'desi ghee', 'dairy', 'cooking', 'amul'],
    price: 675,
    originalPrice: 799,
    discount: '15% OFF',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Oils & Ghee',
    rating: 4.9,
    numReviews: 430,
    sold: 2100,
    stock: 140,
    featured: true,
    isNew: false,
  },
  {
    name: 'Raw Organic Wildflower Honey – 500g',
    description: 'Unprocessed pure forest wildflower honey naturally packed with enzymes, pollen, and smooth sweetness.',
    brand: 'Dabur',
    keywords: ['honey', 'organic', 'sweetener', 'raw honey', 'breakfast'],
    price: 349,
    originalPrice: 450,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Breakfast & Spreads',
    rating: 4.8,
    numReviews: 310,
    sold: 1420,
    stock: 110,
    featured: false,
    isNew: false,
  },
  {
    name: 'All-Natural Crunchy Peanut Butter – 1kg',
    description: 'Slow-roasted peanuts with zero added hydrogenated oils, refined sugars, or preservatives. 30g protein per 100g.',
    brand: 'Pintola',
    keywords: ['peanut butter', 'spread', 'protein', 'crunchy', 'breakfast', 'gym'],
    price: 425,
    originalPrice: 550,
    discount: '23% OFF',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Breakfast & Spreads',
    rating: 4.7,
    numReviews: 290,
    sold: 1680,
    stock: 95,
    featured: false,
    isNew: false,
  },
  {
    name: 'Kashmiri Lal Mirch Powder – 250g',
    description: 'Authentic stemless Kashmiri red chillies ground fine to give vibrant crimson color and mild aromatic warmth.',
    brand: 'Everest',
    keywords: ['chilli powder', 'spices', 'kashmiri mirch', 'masala', 'cooking'],
    price: 185,
    originalPrice: 220,
    discount: '16% OFF',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Spices & Masala',
    rating: 4.6,
    numReviews: 140,
    sold: 980,
    stock: 150,
    featured: false,
    isNew: false,
  },
  {
    name: 'Organic Turmeric Powder (Curcumin Rich) – 500g',
    description: 'Golden yellow organic turmeric with minimum 3% natural curcumin for rich flavor and natural immunity.',
    brand: 'Tata Sampann',
    keywords: ['turmeric', 'haldi', 'curcumin', 'spices', 'organic', 'masala'],
    price: 165,
    originalPrice: 210,
    discount: '21% OFF',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Spices & Masala',
    rating: 4.8,
    numReviews: 220,
    sold: 1350,
    stock: 130,
    featured: false,
    isNew: false,
  },
  {
    name: 'Roasted California Almonds – 500g',
    description: 'Crisp, premium jumbo California almonds lightly roasted with a pinch of sea salt. Rich in Vitamin E.',
    brand: 'Happilo',
    keywords: ['almonds', 'dry fruits', 'nuts', 'healthy snacks', 'happilo'],
    price: 499,
    originalPrice: 699,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Snacks & Dry Fruits',
    rating: 4.7,
    numReviews: 380,
    sold: 1950,
    stock: 100,
    featured: true,
    isNew: false,
  },
  {
    name: 'Whole Jumbo Cashews (W240) – 500g',
    description: 'Handpicked premium white whole cashew nuts. Creamy, buttery, and perfect for gourmet cooking and snacking.',
    brand: 'Nutraj',
    keywords: ['cashews', 'kaju', 'dry fruits', 'nuts', 'snacks', 'nutraj'],
    price: 549,
    originalPrice: 750,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1536591375315-1b83884045bd?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Snacks & Dry Fruits',
    rating: 4.8,
    numReviews: 260,
    sold: 1400,
    stock: 75,
    featured: false,
    isNew: false,
  },
  {
    name: 'Darjeeling Green Tea – 100 Tea Bags',
    description: 'Pure whole leaf Darjeeling green tea rich in natural catechins and antioxidants for daily wellness.',
    brand: 'Twinings',
    keywords: ['green tea', 'tea', 'beverages', 'antioxidants', 'darjeeling'],
    price: 399,
    originalPrice: 499,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Beverages',
    rating: 4.6,
    numReviews: 175,
    sold: 860,
    stock: 115,
    featured: false,
    isNew: false,
  },
  {
    name: 'Artisan Roast Arabica Coffee Beans – 500g',
    description: 'Single-origin 100% Arabica medium-dark roast whole beans. Notes of caramel, toasted nuts, and dark cocoa.',
    brand: 'Blue Tokai',
    keywords: ['coffee', 'arabica', 'coffee beans', 'espresso', 'beverages'],
    price: 590,
    originalPrice: 750,
    discount: '21% OFF',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Beverages',
    rating: 4.9,
    numReviews: 410,
    sold: 2300,
    stock: 80,
    featured: true,
    isNew: true,
  },
  {
    name: 'Rolled Oats Whole Grain – 1kg',
    description: 'Thick-cut 100% whole grain rolled oats. Beta-glucan rich for heart health, breakfast porridge, and smoothies.',
    brand: 'Quaker',
    keywords: ['oats', 'rolled oats', 'breakfast', 'cereal', 'fiber', 'healthy'],
    price: 199,
    originalPrice: 260,
    discount: '23% OFF',
    image: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Breakfast & Spreads',
    rating: 4.7,
    numReviews: 320,
    sold: 1740,
    stock: 160,
    featured: false,
    isNew: false,
  },
  {
    name: 'Natural Himalayan Pink Rock Salt – 1kg',
    description: 'Unrefined pink crystal salt mined from ancient seabed deposits, containing 84 trace minerals.',
    brand: 'Tata Salt',
    keywords: ['pink salt', 'rock salt', 'himalayan salt', 'spices', 'mineral salt'],
    price: 120,
    originalPrice: 160,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1607672632458-9eb56696346b?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Spices & Masala',
    rating: 4.8,
    numReviews: 210,
    sold: 1550,
    stock: 180,
    featured: false,
    isNew: false,
  },
  {
    name: 'Dark Chocolate Crunchy Granola – 400g',
    description: 'Toasted rolled oats, crunchy almonds, chia seeds, and 70% dark chocolate chunks sweetened with honey.',
    brand: 'Yoga Bar',
    keywords: ['granola', 'dark chocolate', 'cereal', 'breakfast', 'snacks', 'muesli'],
    price: 325,
    originalPrice: 420,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1517093708146-24e6c3823485?w=600&q=80',
    category: 'Grocery',
    subcategory: 'Breakfast & Spreads',
    rating: 4.7,
    numReviews: 190,
    sold: 990,
    stock: 85,
    featured: false,
    isNew: true,
  },

  // ==========================================
  // 2. SHOES (15 Products)
  // ==========================================
  {
    name: 'Air-Cushion Zoom Running Sneakers',
    description: 'Engineered breathable mesh upper with responsive air-cushioned foam midsole for effortless road running.',
    brand: 'Nike',
    keywords: ['sneakers', 'running shoes', 'sports', 'footwear', 'nike', 'air zoom'],
    price: 3499,
    originalPrice: 4999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Sneakers',
    rating: 4.8,
    numReviews: 520,
    sold: 2100,
    stock: 65,
    featured: true,
    isNew: false,
  },
  {
    name: 'Classic Chelsea Leather Ankle Boots',
    description: 'Handcrafted genuine burnished leather Chelsea boots with elasticated side gussets and durable rubber sole.',
    brand: 'Clarks',
    keywords: ['boots', 'chelsea boots', 'leather', 'men shoes', 'clarks'],
    price: 4299,
    originalPrice: 5999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Boots',
    rating: 4.7,
    numReviews: 230,
    sold: 780,
    stock: 45,
    featured: true,
    isNew: false,
  },
  {
    name: 'Italian Handcrafted Leather Loafers',
    description: 'Sleek slip-on dress loafers made from full-grain calfskin with memory foam footbeds for day-long comfort.',
    brand: 'Woodland',
    keywords: ['loafers', 'formal shoes', 'slip on', 'leather', 'office'],
    price: 3199,
    originalPrice: 4499,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Formal',
    rating: 4.6,
    numReviews: 185,
    sold: 620,
    stock: 50,
    featured: false,
    isNew: false,
  },
  {
    name: 'Minimalist White Streetwear Sneakers',
    description: 'Clean silhouette low-top sneakers in soft vegan leather with contrast heel tab and vulcanized rubber cupsole.',
    brand: 'Adidas',
    keywords: ['sneakers', 'white shoes', 'casual', 'streetwear', 'adidas'],
    price: 2499,
    originalPrice: 3499,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Sneakers',
    rating: 4.7,
    numReviews: 390,
    sold: 1450,
    stock: 80,
    featured: false,
    isNew: true,
  },
  {
    name: 'Waterproof Mountain Hiking Boots',
    description: 'Rugged all-weather boots featuring Gore-Tex water protection, reinforced toe caps, and deep lug traction soles.',
    brand: 'Timberland',
    keywords: ['hiking boots', 'trekking', 'outdoor', 'waterproof', 'timberland'],
    price: 5499,
    originalPrice: 7999,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Boots',
    rating: 4.9,
    numReviews: 190,
    sold: 530,
    stock: 35,
    featured: true,
    isNew: false,
  },
  {
    name: 'Classic Oxford Formal Dress Shoes',
    description: 'Timeless cap-toe closed lacing Oxford shoes crafted from polished genuine leather for weddings and business.',
    brand: 'Bata',
    keywords: ['oxford shoes', 'formal', 'dress shoes', 'leather', 'office wear'],
    price: 2799,
    originalPrice: 3999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Formal',
    rating: 4.5,
    numReviews: 160,
    sold: 690,
    stock: 55,
    featured: false,
    isNew: false,
  },
  {
    name: 'Pointed Toe Stiletto Pumps – 3.5 Inch',
    description: 'Glamorous pointed-toe high heels in glossy patent finish with padded insole and slip-resistant heel tip.',
    brand: 'Steve Madden',
    keywords: ['heels', 'pumps', 'stilettos', 'party wear', 'women shoes'],
    price: 3699,
    originalPrice: 4999,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Heels',
    rating: 4.7,
    numReviews: 240,
    sold: 810,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Strappy Block Heel Party Sandals',
    description: 'Chic dual-strap mid-block heel sandals providing stability and style for evening dinners and festive events.',
    brand: 'Aldo',
    keywords: ['block heels', 'sandals', 'heels', 'strappy sandals', 'party'],
    price: 2899,
    originalPrice: 3799,
    discount: '24% OFF',
    image: 'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Heels',
    rating: 4.6,
    numReviews: 155,
    sold: 470,
    stock: 48,
    featured: false,
    isNew: true,
  },
  {
    name: 'Lightweight Slip-On Memory Walking Shoes',
    description: 'Ultra-flexible knit slip-on walking shoes with air-cooled memory foam insoles. Featherlight everyday shoe.',
    brand: 'Skechers',
    keywords: ['walking shoes', 'slip on', 'sneakers', 'comfortable', 'skechers'],
    price: 2699,
    originalPrice: 3599,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Sneakers',
    rating: 4.8,
    numReviews: 440,
    sold: 1900,
    stock: 70,
    featured: false,
    isNew: false,
  },
  {
    name: 'Ergonomic Cork Footbed Slide Sandals',
    description: 'Dual adjustable buckle straps on an anatomical natural cork footbed that molds to your feet over time.',
    brand: 'Birkenstock',
    keywords: ['sandals', 'slides', 'cork footbed', 'casual', 'birkenstock'],
    price: 3299,
    originalPrice: 4299,
    discount: '23% OFF',
    image: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Sandals',
    rating: 4.7,
    numReviews: 290,
    sold: 1100,
    stock: 55,
    featured: false,
    isNew: false,
  },
  {
    name: 'Retro Canvas High-Top Sneakers',
    description: 'Vintage-inspired heavy cotton canvas sneakers with durable vulcanized waffle rubber outsole.',
    brand: 'Converse',
    keywords: ['canvas shoes', 'sneakers', 'high top', 'vintage', 'converse'],
    price: 2199,
    originalPrice: 2999,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Sneakers',
    rating: 4.6,
    numReviews: 320,
    sold: 1350,
    stock: 65,
    featured: false,
    isNew: false,
  },
  {
    name: 'Rugged Military Combat Ankle Boots',
    description: 'Heavy-duty matte black leather lace-up combat boots with side zipper access and oil-resistant grip tread.',
    brand: 'Red Tape',
    keywords: ['combat boots', 'boots', 'leather', 'military style', 'biker'],
    price: 3899,
    originalPrice: 5299,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Boots',
    rating: 4.5,
    numReviews: 180,
    sold: 720,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Breathable Perforated Leather Derby Shoes',
    description: 'Modern derby dress shoes with subtle laser-cut perforations for all-day ventilation during office hours.',
    brand: 'Hush Puppies',
    keywords: ['derby shoes', 'formal', 'office', 'leather', 'breathable'],
    price: 2999,
    originalPrice: 4199,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Formal',
    rating: 4.6,
    numReviews: 140,
    sold: 580,
    stock: 45,
    featured: false,
    isNew: false,
  },
  {
    name: 'Ankle Strap Evening Wedge Espadrilles',
    description: 'Natural jute rope wrapped wedge heels with soft suede upper and delicate gold-buckle ankle wrap.',
    brand: 'Charles & Keith',
    keywords: ['wedges', 'heels', 'espadrilles', 'summer shoes', 'sandals'],
    price: 2799,
    originalPrice: 3699,
    discount: '24% OFF',
    image: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Heels',
    rating: 4.7,
    numReviews: 175,
    sold: 630,
    stock: 35,
    featured: false,
    isNew: true,
  },
  {
    name: 'All-Terrain Adventure Trekking Sandals',
    description: 'Quick-drying hydrophobic webbing sandals with cushioned EVA midsole and multidirectional lug grip.',
    brand: 'Crocs',
    keywords: ['trekking sandals', 'outdoor', 'waterproof', 'sandals', 'adventure'],
    price: 1899,
    originalPrice: 2499,
    discount: '24% OFF',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    category: 'Shoes',
    subcategory: 'Sandals',
    rating: 4.6,
    numReviews: 210,
    sold: 950,
    stock: 75,
    featured: false,
    isNew: false,
  },

  // ==========================================
  // 3. APPAREL (15 Products)
  // ==========================================
  {
    name: 'Classic Oxford Button-Down Shirt',
    description: 'Crisp 100% combed cotton Oxford shirt with tailored collar and mother-of-pearl buttons for smart-casual wear.',
    brand: 'Arrow',
    keywords: ['shirt', 'oxford shirt', 'men clothing', 'cotton', 'formal', 'arrow'],
    price: 1499,
    originalPrice: 1999,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80',
    category: 'Apparel',
    subcategory: "Men's Shirts",
    rating: 4.6,
    numReviews: 310,
    sold: 1450,
    stock: 85,
    featured: true,
    isNew: false,
  },
  {
    name: 'Summer Breeze Floral Tiered Midi Dress',
    description: 'Lightweight breathable rayon dress with floral botanical print, sweetheart neckline, and flattering tiered hem.',
    brand: 'Zara',
    keywords: ['dress', 'floral dress', 'summer dress', 'midi dress', 'women wear'],
    price: 2299,
    originalPrice: 3299,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1495385794356-15371f348c31?w=600&q=80',
    category: 'Apparel',
    subcategory: "Women's Dresses",
    rating: 4.8,
    numReviews: 420,
    sold: 1890,
    stock: 60,
    featured: true,
    isNew: false,
  },
  {
    name: 'Vintage Wash Denim Trucker Jacket',
    description: 'Heavyweight rigid indigo denim jacket with brass button closure, flap chest pockets, and timeless vintage wash.',
    brand: "Levi's",
    keywords: ['denim jacket', 'jacket', 'jeans jacket', 'outerwear', 'levis'],
    price: 3499,
    originalPrice: 4999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Jackets & Coats',
    rating: 4.9,
    numReviews: 530,
    sold: 2150,
    stock: 45,
    featured: true,
    isNew: false,
  },
  {
    name: 'Slim-Fit Stretch Cotton Chinos',
    description: 'Mid-rise flat-front chino trousers with 2% elastane flex stretch. Smooth twill weave for office or dinner.',
    brand: 'Dockers',
    keywords: ['chinos', 'pants', 'trousers', 'cotton pants', 'dockers'],
    price: 1899,
    originalPrice: 2699,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80',
    category: 'Apparel',
    subcategory: "Men's Pants",
    rating: 4.5,
    numReviews: 240,
    sold: 1100,
    stock: 70,
    featured: false,
    isNew: false,
  },
  {
    name: 'Ribbed Cotton Scoop-Neck Top',
    description: 'Soft organic ribbed cotton knit top featuring short sleeves and a flattering fitted scoop neckline.',
    brand: 'H&M',
    keywords: ['top', 'tshirt', 'women top', 'ribbed', 'casual', 'hm'],
    price: 699,
    originalPrice: 999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
    category: 'Apparel',
    subcategory: "Women's Tops",
    rating: 4.6,
    numReviews: 280,
    sold: 1350,
    stock: 90,
    featured: false,
    isNew: true,
  },
  {
    name: 'High-Waisted Seamless Yoga Leggings',
    description: 'Four-way stretch squat-proof athletic tights with tummy control waistband and moisture-wicking quick-dry fabric.',
    brand: 'Lululemon',
    keywords: ['leggings', 'yoga pants', 'activewear', 'gym tights', 'lululemon'],
    price: 2199,
    originalPrice: 2999,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Activewear',
    rating: 4.8,
    numReviews: 480,
    sold: 2300,
    stock: 80,
    featured: true,
    isNew: false,
  },
  {
    name: "Men's Genuine Leather Biker Jacket",
    description: 'Supple full-grain lambskin biker jacket with asymmetrical heavy metal zip and quilted diamond satin lining.',
    brand: 'Wrangler',
    keywords: ['leather jacket', 'biker jacket', 'motorcycle', 'jacket', 'outerwear'],
    price: 6499,
    originalPrice: 8999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Jackets & Coats',
    rating: 4.7,
    numReviews: 210,
    sold: 640,
    stock: 25,
    featured: false,
    isNew: false,
  },
  {
    name: 'Satin Wrap Evening Maxi Dress',
    description: 'Luxurious silky satin wrap dress with waist tie belt, flowing flutter sleeves, and graceful side slit.',
    brand: 'Mango',
    keywords: ['maxi dress', 'satin dress', 'party dress', 'evening gown', 'mango'],
    price: 2999,
    originalPrice: 4299,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80',
    category: 'Apparel',
    subcategory: "Women's Dresses",
    rating: 4.7,
    numReviews: 190,
    sold: 720,
    stock: 35,
    featured: false,
    isNew: true,
  },
  {
    name: 'Pure Linen Mandarin Collar Shirt',
    description: 'Breezy 100% natural European flax linen shirt with band collar for warm summer evenings and tropical holidays.',
    brand: 'Peter England',
    keywords: ['linen shirt', 'mandarin collar', 'men shirt', 'summer wear'],
    price: 1799,
    originalPrice: 2499,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80',
    category: 'Apparel',
    subcategory: "Men's Shirts",
    rating: 4.5,
    numReviews: 165,
    sold: 840,
    stock: 55,
    featured: false,
    isNew: false,
  },
  {
    name: 'Dri-FIT Breathable Running Shorts',
    description: '7-inch inseam athletic shorts with built-in compression liner, zippered phone pocket, and reflective accents.',
    brand: 'Nike',
    keywords: ['running shorts', 'activewear', 'gym shorts', 'sports', 'nike'],
    price: 1399,
    originalPrice: 1899,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Activewear',
    rating: 4.7,
    numReviews: 290,
    sold: 1420,
    stock: 75,
    featured: false,
    isNew: false,
  },
  {
    name: 'Cable-Knit Pure Wool Pullover Sweater',
    description: 'Chunky textured crewneck knit sweater crafted from soft merino wool blend to keep you cozy during winter.',
    brand: 'United Colors of Benetton',
    keywords: ['sweater', 'pullover', 'wool', 'winter wear', 'knitwear'],
    price: 2499,
    originalPrice: 3499,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Jackets & Coats',
    rating: 4.8,
    numReviews: 215,
    sold: 890,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Tailored Straight-Fit Formal Trousers',
    description: 'Wrinkle-resistant poly-viscose formal trousers with crease preservation line and comfortable stretch waistband.',
    brand: 'Raymond',
    keywords: ['formal pants', 'trousers', 'office wear', 'suit pants', 'raymond'],
    price: 1699,
    originalPrice: 2299,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
    category: 'Apparel',
    subcategory: "Men's Pants",
    rating: 4.6,
    numReviews: 180,
    sold: 910,
    stock: 65,
    featured: false,
    isNew: false,
  },
  {
    name: 'Ruffled Chiffon Party Blouse',
    description: 'Ethereal sheer chiffon evening blouse with delicate front ruffles, bishop sleeves, and buttoned cuffs.',
    brand: 'ONLY',
    keywords: ['blouse', 'chiffon', 'party top', 'women shirt', 'only'],
    price: 1299,
    originalPrice: 1799,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80',
    category: 'Apparel',
    subcategory: "Women's Tops",
    rating: 4.6,
    numReviews: 145,
    sold: 630,
    stock: 50,
    featured: false,
    isNew: true,
  },
  {
    name: 'Oversized Heavy Fleece Graphic Hoodie',
    description: '400 GSM heavyweight French terry cotton hoodie with kangaroo pocket, double-layered hood, and relaxed drop shoulders.',
    brand: 'Puma',
    keywords: ['hoodie', 'sweatshirt', 'fleece', 'streetwear', 'puma'],
    price: 2199,
    originalPrice: 2999,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Jackets & Coats',
    rating: 4.7,
    numReviews: 350,
    sold: 1600,
    stock: 55,
    featured: false,
    isNew: false,
  },
  {
    name: 'Thermal Compression Gym Baselayer Top',
    description: 'Ergonomic targeted muscle support compression longsleeve top designed for cold weather outdoor workouts.',
    brand: 'Under Armour',
    keywords: ['compression top', 'gym wear', 'activewear', 'thermal', 'under armour'],
    price: 1899,
    originalPrice: 2599,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80',
    category: 'Apparel',
    subcategory: 'Activewear',
    rating: 4.8,
    numReviews: 270,
    sold: 1150,
    stock: 60,
    featured: false,
    isNew: false,
  },

  // ==========================================
  // 4. BAKERY (15 Products)
  // ==========================================
  {
    name: 'Belgian Dark Chocolate Truffle Cake – 1kg',
    description: 'Triple-layer Dutch sponge soaked in espresso ganache, coated with 70% dark Belgian chocolate silk glaze.',
    brand: 'MegaBakery',
    keywords: ['chocolate cake', 'truffle cake', 'bakery', 'birthday cake', 'dessert'],
    price: 1299,
    originalPrice: 1699,
    discount: '24% OFF',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cakes',
    rating: 4.9,
    numReviews: 540,
    sold: 2450,
    stock: 25,
    featured: true,
    isNew: false,
  },
  {
    name: 'Artisanal French Sourdough Country Loaf – 450g',
    description: 'Fermented naturally for 36 hours. Crisp caramelized crust with open, chewy crumb and delicate tart acidity.',
    brand: 'The French Baker',
    keywords: ['sourdough', 'bread', 'artisanal bread', 'bakery', 'french loaf'],
    price: 180,
    originalPrice: 240,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Breads',
    rating: 4.8,
    numReviews: 290,
    sold: 1680,
    stock: 45,
    featured: true,
    isNew: false,
  },
  {
    name: 'Fresh Almond Butter Croissants – Pack of 4',
    description: 'Flaky 27-layer laminated French croissants filled with rich frangipane almond cream and toasted almond flakes.',
    brand: 'Sweet Treats',
    keywords: ['croissant', 'pastry', 'almond croissant', 'breakfast', 'french bakery'],
    price: 349,
    originalPrice: 449,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Pastries',
    rating: 4.8,
    numReviews: 380,
    sold: 1420,
    stock: 35,
    featured: true,
    isNew: false,
  },
  {
    name: 'Red Velvet Cream Cheese Layer Cake – 1kg',
    description: 'Velvety cocoa-infused red sponge layered with smooth tangy Philadelphia cream cheese frosting.',
    brand: 'MegaBakery',
    keywords: ['red velvet', 'cake', 'cream cheese', 'birthday cake', 'bakery'],
    price: 1199,
    originalPrice: 1499,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cakes',
    rating: 4.7,
    numReviews: 310,
    sold: 1250,
    stock: 20,
    featured: false,
    isNew: false,
  },
  {
    name: 'Gourmet Wild Blueberry Muffins – Pack of 6',
    description: 'Soft bakery muffins bursting with whole Canadian wild blueberries and sprinkled with turbinado sugar crunch.',
    brand: 'Sweet Treats',
    keywords: ['muffins', 'blueberry muffin', 'pastry', 'breakfast', 'sweet'],
    price: 299,
    originalPrice: 399,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Pastries',
    rating: 4.6,
    numReviews: 240,
    sold: 1180,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Chunky Belgian Chocochip Cookies – 300g',
    description: 'Soft-baked butter cookies packed with melted Belgian milk and dark chocolate chunks. Chewy in the middle.',
    brand: 'Cookie Man',
    keywords: ['cookies', 'chocochip', 'biscuits', 'baked snacks', 'cookie man'],
    price: 249,
    originalPrice: 320,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cookies & Biscuits',
    rating: 4.7,
    numReviews: 410,
    sold: 1950,
    stock: 65,
    featured: false,
    isNew: false,
  },
  {
    name: 'Multigrain 7-Seed Farmhouse Bread – 500g',
    description: 'Wholesome loaf topped with flax, sunflower, pumpkin, chia, sesame, poppy, and melon seeds.',
    brand: 'The French Baker',
    keywords: ['bread', 'multigrain bread', 'healthy bread', 'bakery', 'loaf'],
    price: 95,
    originalPrice: 120,
    discount: '21% OFF',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Breads',
    rating: 4.6,
    numReviews: 180,
    sold: 1450,
    stock: 50,
    featured: false,
    isNew: false,
  },
  {
    name: 'Classic Italian Tiramisu Cup – 2 Slices',
    description: 'Espresso-dipped savoiardi ladyfingers layered with fluffy mascarpone cream and dusted with Dutch cocoa.',
    brand: 'Dolce Vita',
    keywords: ['tiramisu', 'italian dessert', 'mascarpone', 'pastry', 'espresso'],
    price: 399,
    originalPrice: 499,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Pastries',
    rating: 4.9,
    numReviews: 290,
    sold: 960,
    stock: 30,
    featured: false,
    isNew: true,
  },
  {
    name: 'Danish Cinnamon Swirl Rolls – Pack of 4',
    description: 'Warm, spiced Ceylon cinnamon rolls topped with sweet vanilla cream cheese frosting drizzle.',
    brand: 'Sweet Treats',
    keywords: ['cinnamon rolls', 'danish', 'pastry', 'cinnamon bun', 'sweet'],
    price: 279,
    originalPrice: 350,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Pastries',
    rating: 4.8,
    numReviews: 220,
    sold: 1050,
    stock: 35,
    featured: false,
    isNew: false,
  },
  {
    name: 'Fresh Alpine Strawberry Glazed Tart – 500g',
    description: 'Crisp buttery shortcrust pastry filled with vanilla bean pastry cream and fresh ruby strawberries.',
    brand: 'MegaBakery',
    keywords: ['strawberry tart', 'fruit tart', 'cake', 'bakery', 'dessert'],
    price: 599,
    originalPrice: 750,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cakes',
    rating: 4.7,
    numReviews: 160,
    sold: 670,
    stock: 25,
    featured: false,
    isNew: true,
  },
  {
    name: 'Pure Butter Scottish Shortbread – 250g',
    description: 'Melt-in-mouth traditional Scottish shortbread fingers baked using pure churned butter and fine cane sugar.',
    brand: 'Walkers',
    keywords: ['shortbread', 'butter cookies', 'biscuits', 'tea snacks', 'walkers'],
    price: 349,
    originalPrice: 420,
    discount: '17% OFF',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cookies & Biscuits',
    rating: 4.8,
    numReviews: 210,
    sold: 890,
    stock: 55,
    featured: false,
    isNew: false,
  },
  {
    name: 'Rustic Herb & Roasted Garlic Focaccia – 350g',
    description: 'Extra virgin olive oil soaked Italian flatbread dimpled with roasted garlic cloves, rosemary, and sea salt.',
    brand: 'The French Baker',
    keywords: ['focaccia', 'garlic bread', 'italian bread', 'focaccia loaf', 'bakery'],
    price: 160,
    originalPrice: 200,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Breads',
    rating: 4.7,
    numReviews: 140,
    sold: 720,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Dutch Double Chocolate Brownies – Pack of 6',
    description: 'Decadent dense fudge brownies with crackly shiny tops, filled with melted dark chocolate buttons.',
    brand: 'Sweet Treats',
    keywords: ['brownies', 'chocolate brownie', 'fudge', 'pastry', 'dessert'],
    price: 349,
    originalPrice: 450,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Pastries',
    rating: 4.8,
    numReviews: 330,
    sold: 1540,
    stock: 35,
    featured: false,
    isNew: false,
  },
  {
    name: 'New York Baked Cheesecake Slice – Pack of 2',
    description: 'Dense and creamy Philadelphia cheesecake on a crunchy graham cracker crust with raspberry coulis.',
    brand: 'MegaBakery',
    keywords: ['cheesecake', 'new york cheesecake', 'cake', 'dessert', 'bakery'],
    price: 499,
    originalPrice: 620,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cakes',
    rating: 4.9,
    numReviews: 360,
    sold: 1400,
    stock: 30,
    featured: false,
    isNew: false,
  },
  {
    name: 'Spiced Rolled Oatmeal Raisin Cookies – 300g',
    description: 'Hearty whole grain rolled oat cookies baked with plump golden raisins and aromatic nutmeg spice.',
    brand: 'Sunfeast',
    keywords: ['oatmeal cookies', 'raisin cookies', 'healthy biscuits', 'bakery'],
    price: 199,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80',
    category: 'Bakery',
    subcategory: 'Cookies & Biscuits',
    rating: 4.6,
    numReviews: 180,
    sold: 840,
    stock: 60,
    featured: false,
    isNew: false,
  },

  // ==========================================
  // 5. STATIONERY (15 Products)
  // ==========================================
  {
    name: 'Premium Brass Fountain Pen – Blue Ink',
    description: 'Weighted solid brass barrel with fine-point stainless steel nib and dual ink cartridge converter system.',
    brand: 'Parker',
    keywords: ['fountain pen', 'pen', 'stationery', 'executive pen', 'parker'],
    price: 1499,
    originalPrice: 1999,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Pens & Pencils',
    rating: 4.8,
    numReviews: 310,
    sold: 1200,
    stock: 55,
    featured: true,
    isNew: false,
  },
  {
    name: 'A5 Handcrafted Leather-Bound Journal Notebook',
    description: 'Genuine buffalo leather journal with 200 unlined archival ivory cotton pages and wrap-around tie strap.',
    brand: 'Moleskine',
    keywords: ['notebook', 'journal', 'leather diary', 'stationery', 'moleskine'],
    price: 799,
    originalPrice: 1199,
    discount: '33% OFF',
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Notebooks & Diaries',
    rating: 4.8,
    numReviews: 440,
    sold: 1850,
    stock: 75,
    featured: true,
    isNew: false,
  },
  {
    name: 'Artist Grade Watercolor Cake Set – 36 Colors',
    description: 'Highly pigmented luminous watercolor pans with built-in mixing palette and refillable water brush pen.',
    brand: 'Faber-Castell',
    keywords: ['watercolors', 'art supplies', 'painting', 'sketching', 'faber castell'],
    price: 899,
    originalPrice: 1250,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Art Supplies',
    rating: 4.7,
    numReviews: 290,
    sold: 940,
    stock: 60,
    featured: false,
    isNew: true,
  },
  {
    name: 'Ergonomic 6-Compartment Metal Mesh Desk Organizer',
    description: 'Powder-coated steel mesh organizer with sliding pen drawer, sticky note dock, and file sorter slots.',
    brand: 'Classmate',
    keywords: ['desk organizer', 'office supplies', 'stationery', 'desk tidy'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Desk Accessories',
    rating: 4.6,
    numReviews: 210,
    sold: 1100,
    stock: 90,
    featured: false,
    isNew: false,
  },
  {
    name: 'Smooth Fine Tip Gel Rollerball Pens – Pack of 10',
    description: '0.5mm precision needle point with Japanese quick-dry smudge-proof ink for clean document writing.',
    brand: 'Pilot',
    keywords: ['gel pens', 'rollerball', 'pens', 'pilot', 'writing instruments'],
    price: 349,
    originalPrice: 450,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1585336261026-7f4175390098?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Pens & Pencils',
    rating: 4.7,
    numReviews: 360,
    sold: 2100,
    stock: 140,
    featured: false,
    isNew: false,
  },
  {
    name: 'Hardcover Undated Weekly Productivity Planner',
    description: 'Goal-setting planner with habit tracker, weekly spreads, ribbon bookmark, and back document pouch.',
    brand: 'Paperkraft',
    keywords: ['planner', 'productivity diary', 'organizer', 'notebook', 'stationery'],
    price: 649,
    originalPrice: 899,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Notebooks & Diaries',
    rating: 4.8,
    numReviews: 195,
    sold: 830,
    stock: 70,
    featured: false,
    isNew: false,
  },
  {
    name: 'Dual-Tip Artist Alcohol Markers – Set of 48',
    description: 'Chisel and fine tip permanent alcohol sketch markers with seamless blending ink and carrying case.',
    brand: 'Touch',
    keywords: ['alcohol markers', 'sketch pens', 'drawing', 'art supplies', 'design'],
    price: 1399,
    originalPrice: 1999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1569683795645-b62e50fbf103?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Art Supplies',
    rating: 4.7,
    numReviews: 240,
    sold: 720,
    stock: 50,
    featured: true,
    isNew: false,
  },
  {
    name: 'Solid Natural Bamboo Desktop Stationery Stand',
    description: 'Eco-friendly polished natural bamboo organizer with phone docking slot and multi-pen wells.',
    brand: 'MegaMart',
    keywords: ['bamboo stand', 'desk organizer', 'office accessories', 'stationery'],
    price: 599,
    originalPrice: 799,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Desk Accessories',
    rating: 4.5,
    numReviews: 140,
    sold: 590,
    stock: 65,
    featured: false,
    isNew: false,
  },
  {
    name: 'Technical Drafting Mechanical Pencil 0.5mm',
    description: 'All-metal knurled brass grip mechanical pencil with lead hardness indicator and cushioned lead mechanism.',
    brand: 'Rotring',
    keywords: ['mechanical pencil', 'drafting pencil', 'rotring', 'sketching pencil'],
    price: 749,
    originalPrice: 950,
    discount: '21% OFF',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Pens & Pencils',
    rating: 4.9,
    numReviews: 220,
    sold: 860,
    stock: 60,
    featured: false,
    isNew: false,
  },
  {
    name: 'Spiral-Bound Heavyweight Sketchbook – 180 GSM',
    description: 'A4 size 80 pages acid-free cold-pressed paper suitable for charcoal, graphite, ink, and light wash.',
    brand: 'Brustro',
    keywords: ['sketchbook', 'drawing pad', 'art paper', 'brustro', 'artist'],
    price: 449,
    originalPrice: 599,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Art Supplies',
    rating: 4.7,
    numReviews: 310,
    sold: 1400,
    stock: 85,
    featured: false,
    isNew: false,
  },
  {
    name: 'Bullet Dotted Grid Hardcover Journal – 120 GSM',
    description: 'Numbered pages with dot grid matrix, dual page markers, and elastic enclosure band for bullet journaling.',
    brand: 'Scribbles',
    keywords: ['bullet journal', 'dot grid', 'journal', 'diary', 'stationery'],
    price: 549,
    originalPrice: 749,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Notebooks & Diaries',
    rating: 4.8,
    numReviews: 260,
    sold: 1120,
    stock: 70,
    featured: false,
    isNew: true,
  },
  {
    name: 'Executive Chrome Finish Ballpoint Pen in Gift Box',
    description: 'Twist-action polished chrome pen with black medium-point refill. Comes in an elegant padded presentation case.',
    brand: 'Cross',
    keywords: ['ballpoint pen', 'luxury pen', 'gift pen', 'executive pen', 'cross'],
    price: 1199,
    originalPrice: 1599,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Pens & Pencils',
    rating: 4.7,
    numReviews: 170,
    sold: 680,
    stock: 45,
    featured: false,
    isNew: false,
  },
  {
    name: 'Heavy Body Acrylic Paint Tubes – Set of 24',
    description: 'Rich satiny consistency artist acrylics with excellent lightfastness and non-fading vivid pigment load.',
    brand: 'Camlin',
    keywords: ['acrylic paint', 'painting colors', 'canvas art', 'art supplies'],
    price: 699,
    originalPrice: 950,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Art Supplies',
    rating: 4.6,
    numReviews: 280,
    sold: 1300,
    stock: 75,
    featured: false,
    isNew: false,
  },
  {
    name: 'Ergonomic Aluminum Foldable Laptop Stand',
    description: 'Sturdy aircraft-grade aluminum riser with anti-slip silicone pads and 6-level tilt elevation for desk posture.',
    brand: 'Portronics',
    keywords: ['laptop stand', 'desk accessories', 'ergonomic', 'office setup'],
    price: 899,
    originalPrice: 1299,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Desk Accessories',
    rating: 4.8,
    numReviews: 510,
    sold: 2200,
    stock: 95,
    featured: false,
    isNew: false,
  },
  {
    name: 'Pastel Sticky Notes & Page Markers Dispenser',
    description: 'Assorted soft pastel sticky note pads with durable transparent film index tabs for book annotation.',
    brand: '3M Post-it',
    keywords: ['sticky notes', 'page flags', 'index tabs', 'stationery', 'post it'],
    price: 249,
    originalPrice: 320,
    discount: '22% OFF',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&q=80',
    category: 'Stationery',
    subcategory: 'Desk Accessories',
    rating: 4.6,
    numReviews: 190,
    sold: 1400,
    stock: 120,
    featured: false,
    isNew: false,
  },

  // ==========================================
  // 6. SPORTS (15 Products)
  // ==========================================
  {
    name: 'Professional Non-Slip TPE Yoga Mat – 6mm',
    description: 'Eco-friendly odorless dual-layer textured TPE mat with body alignment lines and carry strap included.',
    brand: 'Decathlon',
    keywords: ['yoga mat', 'fitness', 'exercise mat', 'workout', 'decathlon'],
    price: 1499,
    originalPrice: 1999,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80',
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.8,
    numReviews: 450,
    sold: 1950,
    stock: 80,
    featured: true,
    isNew: false,
  },
  {
    name: 'Adjustable Cast Iron Dumbbell Set – 20kg',
    description: 'Solid cast iron weight plates with spin-lock threaded chrome bars and knurled ergonomic hand grip.',
    brand: 'Nivia',
    keywords: ['dumbbells', 'weights', 'gym equipment', 'home workout', 'fitness'],
    price: 2899,
    originalPrice: 3999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.7,
    numReviews: 320,
    sold: 1100,
    stock: 40,
    featured: true,
    isNew: false,
  },
  {
    name: 'FIFA Pro Quality Match Football – Size 5',
    description: 'Thermally bonded seamless polyurethane football with textured aerodynamic casing for true flight accuracy.',
    brand: 'Cosco',
    keywords: ['football', 'soccer ball', 'team sports', 'size 5 football', 'cosco'],
    price: 1199,
    originalPrice: 1599,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&q=80',
    category: 'Sports',
    subcategory: 'Team Sports',
    rating: 4.6,
    numReviews: 260,
    sold: 1350,
    stock: 65,
    featured: false,
    isNew: false,
  },
  {
    name: 'High-Modulus Carbon Badminton Racket Set',
    description: 'Twin pack isometric carbon fiber rackets strung at 26 lbs, paired with 6 durable feather shuttlecocks and bag.',
    brand: 'Yonex',
    keywords: ['badminton', 'racket', 'shuttlecock', 'yonex', 'racket sports'],
    price: 2499,
    originalPrice: 3499,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80',
    category: 'Sports',
    subcategory: 'Racket Sports',
    rating: 4.8,
    numReviews: 390,
    sold: 1720,
    stock: 55,
    featured: true,
    isNew: false,
  },
  {
    name: 'Waterproof 3-Person Dome Camping Tent',
    description: 'Double-walled windproof tent with 3000mm hydrostatic head waterproof coating and pop-up fiberglass poles.',
    brand: 'Quechua',
    keywords: ['camping tent', 'outdoor', 'hiking', 'trekking tent', 'quechua'],
    price: 3999,
    originalPrice: 5499,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
    category: 'Sports',
    subcategory: 'Outdoor & Camping',
    rating: 4.7,
    numReviews: 180,
    sold: 520,
    stock: 30,
    featured: false,
    isNew: true,
  },
  {
    name: 'Anti-Fog Mirrored Swimming Goggles',
    description: 'Wide-angle panoramic UV-protected lenses with soft silicone eye gaskets and quick-fit buckle strap.',
    brand: 'Speedo',
    keywords: ['swimming goggles', 'swim gear', 'swimming', 'anti fog', 'speedo'],
    price: 899,
    originalPrice: 1299,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80',
    category: 'Sports',
    subcategory: 'Swimming',
    rating: 4.7,
    numReviews: 280,
    sold: 1250,
    stock: 85,
    featured: false,
    isNew: false,
  },
  {
    name: 'High-Density Deep Tissue Foam Roller – 45cm',
    description: 'Molded foam trigger point roller for myofascial release, muscle soreness recovery, and back rehabilitation.',
    brand: 'Decathlon',
    keywords: ['foam roller', 'massage roller', 'recovery', 'fitness', 'gym'],
    price: 799,
    originalPrice: 1099,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80',
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.6,
    numReviews: 210,
    sold: 980,
    stock: 70,
    featured: false,
    isNew: false,
  },
  {
    name: 'Pro Official Composite Basketball – Size 7',
    description: 'Indoor/outdoor composite leather basketball with deep pebbled channels for supreme shooting grip.',
    brand: 'Spalding',
    keywords: ['basketball', 'spalding', 'team sports', 'size 7 basketball'],
    price: 1699,
    originalPrice: 2299,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=600&q=80',
    category: 'Sports',
    subcategory: 'Team Sports',
    rating: 4.8,
    numReviews: 310,
    sold: 1400,
    stock: 60,
    featured: false,
    isNew: false,
  },
  {
    name: '5-Piece Heavy Duty Resistance Bands Set',
    description: '100% natural latex stackable resistance exercise tubes ranging from 10 lbs to 50 lbs with ankle straps and door anchor.',
    brand: 'Boldfit',
    keywords: ['resistance bands', 'workout bands', 'gym equipment', 'fitness'],
    price: 799,
    originalPrice: 1199,
    discount: '33% OFF',
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&q=80',
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.7,
    numReviews: 480,
    sold: 2600,
    stock: 110,
    featured: false,
    isNew: false,
  },
  {
    name: 'Tour Graphite Tennis Racket with Cover',
    description: 'Lightweight carbon composite frame with 100 sq inch head size providing large sweet spot and spin control.',
    brand: 'Wilson',
    keywords: ['tennis racket', 'tennis', 'wilson', 'racket sports', 'tour racket'],
    price: 3899,
    originalPrice: 5299,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=600&q=80',
    category: 'Sports',
    subcategory: 'Racket Sports',
    rating: 4.8,
    numReviews: 170,
    sold: 610,
    stock: 35,
    featured: false,
    isNew: true,
  },
  {
    name: 'Ultra-Light Thermal Sleeping Bag – 0°C',
    description: 'Mummy-style 400T ripstop nylon sleeping bag with hollow-fiber synthetic insulation and draft collar.',
    brand: 'Wildcraft',
    keywords: ['sleeping bag', 'camping', 'trekking', 'outdoor gear', 'wildcraft'],
    price: 2199,
    originalPrice: 2999,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&q=80',
    category: 'Sports',
    subcategory: 'Outdoor & Camping',
    rating: 4.6,
    numReviews: 145,
    sold: 490,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Insulated Stainless Steel Sports Bottle – 1L',
    description: 'Double-wall vacuum insulated flask keeping water ice-cold for 24 hours. Chug cap with silicone carrying loop.',
    brand: 'Milton',
    keywords: ['water bottle', 'gym bottle', 'insulated bottle', 'sports bottle'],
    price: 699,
    originalPrice: 999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.8,
    numReviews: 530,
    sold: 2800,
    stock: 130,
    featured: false,
    isNew: false,
  },
  {
    name: 'Silicone Swim Cap & Ergonomic Earplugs Combo',
    description: 'Tear-resistant hypoallergenic 100% silicone swim cap that protects hair from chlorinated pool water.',
    brand: 'Speedo',
    keywords: ['swim cap', 'earplugs', 'swimming accessories', 'pool gear'],
    price: 399,
    originalPrice: 550,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80',
    category: 'Sports',
    subcategory: 'Swimming',
    rating: 4.5,
    numReviews: 190,
    sold: 950,
    stock: 90,
    featured: false,
    isNew: false,
  },
  {
    name: 'Kashmir Willow Cricket Bat Full Size (SH)',
    description: 'Selected grade Kashmir willow bat with thick contoured edges, cane handle, and rubber toe guard protection.',
    brand: 'SG',
    keywords: ['cricket bat', 'cricket', 'sg cricket', 'team sports', 'sports'],
    price: 1899,
    originalPrice: 2599,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80',
    category: 'Sports',
    subcategory: 'Team Sports',
    rating: 4.7,
    numReviews: 340,
    sold: 1560,
    stock: 50,
    featured: false,
    isNew: false,
  },
  {
    name: 'Digital Speed Jump Rope with Calorie Counter',
    description: 'Tangle-free steel wire jump rope with 360-degree ball bearings and LCD handle display counting jumps and calories.',
    brand: 'Strauss',
    keywords: ['jump rope', 'skipping rope', 'cardio', 'fitness', 'weight loss'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80',
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.6,
    numReviews: 230,
    sold: 1100,
    stock: 85,
    featured: false,
    isNew: true,
  },

  // ==========================================
  // 7. FURNITURE (15 Products)
  // ==========================================
  {
    name: 'Ergonomic High-Back Mesh Office Chair',
    description: 'Breathable Korean mesh with 3D adjustable armrests, synchronized tilt mechanism, and dynamic lumbar support.',
    brand: 'Green Soul',
    keywords: ['office chair', 'ergonomic chair', 'desk chair', 'furniture', 'wfh'],
    price: 8999,
    originalPrice: 12999,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Office',
    rating: 4.8,
    numReviews: 480,
    sold: 1650,
    stock: 35,
    featured: true,
    isNew: false,
  },
  {
    name: 'Mid-Century 3-Seater Fabric Sofa',
    description: 'High-resilience foam cushions upholstered in stain-resistant linen fabric with solid tapered walnut wood legs.',
    brand: 'Urban Ladder',
    keywords: ['sofa', '3 seater sofa', 'couch', 'living room', 'urban ladder'],
    price: 18999,
    originalPrice: 26999,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Living Room',
    rating: 4.8,
    numReviews: 310,
    sold: 720,
    stock: 18,
    featured: true,
    isNew: false,
  },
  {
    name: 'Solid Sheesham Wood Coffee Table',
    description: 'Handcrafted solid Indian rosewood coffee table with warm natural grain finish and open bottom storage shelf.',
    brand: 'Pepperfry',
    keywords: ['coffee table', 'center table', 'wood table', 'living room furniture'],
    price: 5499,
    originalPrice: 7999,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Living Room',
    rating: 4.7,
    numReviews: 240,
    sold: 890,
    stock: 25,
    featured: false,
    isNew: false,
  },
  {
    name: 'Electric Height-Adjustable Standing Desk',
    description: 'Dual-motor motorized sit-stand desk with digital memory presets, cable tray, and scratch-proof wooden tabletop.',
    brand: 'Jin Office',
    keywords: ['standing desk', 'height adjustable desk', 'office table', 'wfh'],
    price: 16499,
    originalPrice: 22999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Office',
    rating: 4.9,
    numReviews: 275,
    sold: 680,
    stock: 20,
    featured: true,
    isNew: true,
  },
  {
    name: '5-Tier Geometric Bookshelf Storage Display',
    description: 'Industrial matte black metal frame supporting five warm oak-finish engineered wood display shelves.',
    brand: 'Ikea',
    keywords: ['bookshelf', 'storage rack', 'bookcase', 'display shelf', 'ikea'],
    price: 4299,
    originalPrice: 5999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Storage',
    rating: 4.7,
    numReviews: 290,
    sold: 1100,
    stock: 40,
    featured: false,
    isNew: false,
  },
  {
    name: 'Queen Size Solid Teak Wood Bed Frame',
    description: 'Sturdy minimalist platform bed with slanted headboard, underbed clearance, and reinforced wooden slats.',
    brand: 'Urban Ladder',
    keywords: ['queen bed', 'bed frame', 'teak wood bed', 'bedroom furniture'],
    price: 21999,
    originalPrice: 29999,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Bedroom',
    rating: 4.8,
    numReviews: 190,
    sold: 450,
    stock: 15,
    featured: false,
    isNew: false,
  },
  {
    name: 'Plush Velvet Accent Armchair',
    description: 'Curved shell-back lounge armchair with dense foam cushioning and electroplated golden metal legs.',
    brand: 'Home Centre',
    keywords: ['armchair', 'accent chair', 'velvet chair', 'living room chair'],
    price: 7499,
    originalPrice: 9999,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Living Room',
    rating: 4.6,
    numReviews: 215,
    sold: 630,
    stock: 22,
    featured: false,
    isNew: true,
  },
  {
    name: 'Dual-Drawer Compact Bedside Nightstand',
    description: 'Smooth-glide drawer nightstand with sleek chamfered handles and moisture-resistant walnut veneer finish.',
    brand: 'Pepperfry',
    keywords: ['bedside table', 'nightstand', 'bedroom furniture', 'drawer table'],
    price: 2699,
    originalPrice: 3699,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1532372998445-5f6e8384709d?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Bedroom',
    rating: 4.6,
    numReviews: 180,
    sold: 840,
    stock: 45,
    featured: false,
    isNew: false,
  },
  {
    name: '4-Door Wardrobe with Full-Length Mirror',
    description: 'Spacious engineered wood wardrobe featuring internal hanging rods, locker drawer, and adjustable shelving.',
    brand: 'Godrej Interio',
    keywords: ['wardrobe', 'almirah', 'closet', 'storage', 'bedroom furniture'],
    price: 18499,
    originalPrice: 24999,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Storage',
    rating: 4.7,
    numReviews: 160,
    sold: 390,
    stock: 14,
    featured: false,
    isNew: false,
  },
  {
    name: 'Heavy Duty Metal Garment Clothing Rack',
    description: 'Freestanding clothing rail with lower shoe rack and side umbrella/bag hooks. Holds up to 60kg.',
    brand: 'Ikea',
    keywords: ['garment rack', 'clothes rail', 'storage', 'wardrobe organizer'],
    price: 1799,
    originalPrice: 2499,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Storage',
    rating: 4.5,
    numReviews: 240,
    sold: 1280,
    stock: 60,
    featured: false,
    isNew: false,
  },
  {
    name: 'Memory Foam Executive High-Back Chair',
    description: 'Padded bonded leather executive chair with waterfall seat edge, padded armrests, and recline lock.',
    brand: 'Featherlite',
    keywords: ['executive chair', 'office chair', 'leather chair', 'featherlite'],
    price: 11499,
    originalPrice: 15999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1580481077194-c7104b2b0056?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Office',
    rating: 4.8,
    numReviews: 210,
    sold: 580,
    stock: 25,
    featured: false,
    isNew: false,
  },
  {
    name: 'Round Marble-Top Nesting Coffee Tables (Set of 2)',
    description: 'Two interlocking circular tables with Carrara white faux marble tops and powder-coated gold steel bases.',
    brand: 'Nilkamal',
    keywords: ['nesting tables', 'side tables', 'coffee table', 'living room'],
    price: 4999,
    originalPrice: 6999,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Living Room',
    rating: 4.7,
    numReviews: 175,
    sold: 720,
    stock: 30,
    featured: false,
    isNew: true,
  },
  {
    name: 'Solid Wood 6-Seater Dining Table',
    description: 'Robust acacia hardwood dining table with natural live edge contour and sturdy angled trestle base.',
    brand: 'Pepperfry',
    keywords: ['dining table', '6 seater dining', 'wood table', 'kitchen table'],
    price: 19999,
    originalPrice: 27999,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Living Room',
    rating: 4.9,
    numReviews: 185,
    sold: 390,
    stock: 12,
    featured: false,
    isNew: false,
  },
  {
    name: 'Upholstered Ottoman Storage Bed Bench',
    description: 'Tufted linen bedroom end-of-bed bench with pneumatic lift lid revealing deep concealed storage.',
    brand: 'Urban Ladder',
    keywords: ['storage bench', 'ottoman', 'bedroom bench', 'furniture'],
    price: 5299,
    originalPrice: 7299,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Bedroom',
    rating: 4.7,
    numReviews: 140,
    sold: 480,
    stock: 28,
    featured: false,
    isNew: false,
  },
  {
    name: 'Floating Wall-Mounted TV Media Console Unit',
    description: 'Sleek wall console accommodating up to 65" TVs with cable pass-through channels and soft-close cabinets.',
    brand: 'Ikea',
    keywords: ['tv unit', 'media console', 'wall cabinet', 'living room furniture'],
    price: 6499,
    originalPrice: 8999,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80',
    category: 'Furniture',
    subcategory: 'Living Room',
    rating: 4.8,
    numReviews: 260,
    sold: 840,
    stock: 32,
    featured: false,
    isNew: false,
  },

  // ==========================================
  // 8. PLANTS (15 Products)
  // ==========================================
  {
    name: 'Golden Pothos (Money Plant) in Ceramic Pot',
    description: 'Thriving lush variegated heart-shaped leaves that naturally purify indoor air and tolerate low light.',
    brand: 'Ugaoo',
    keywords: ['money plant', 'golden pothos', 'indoor plant', 'air purifier', 'plants'],
    price: 399,
    originalPrice: 599,
    discount: '33% OFF',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&q=80',
    category: 'Plants',
    subcategory: 'Indoor Plants',
    rating: 4.8,
    numReviews: 460,
    sold: 2100,
    stock: 120,
    featured: true,
    isNew: false,
  },
  {
    name: 'Sansevieria Snake Plant Laurentii',
    description: 'Hardy vertical sword-like leaves with yellow borders. NASA-certified nighttime oxygen producing plant.',
    brand: 'Nurserylive',
    keywords: ['snake plant', 'sansevieria', 'indoor plant', 'air purifying', 'nurserylive'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bf6?w=600&q=80',
    category: 'Plants',
    subcategory: 'Indoor Plants',
    rating: 4.9,
    numReviews: 580,
    sold: 2800,
    stock: 140,
    featured: true,
    isNew: false,
  },
  {
    name: 'Exotic Mini Succulents Assorted – Pack of 4',
    description: 'Four distinctive drought-tolerant succulent varieties planted in matching ceramic tabletop cubes.',
    brand: 'Ugaoo',
    keywords: ['succulents', 'mini plants', 'desk plant', 'cactus', 'ugaoo'],
    price: 649,
    originalPrice: 899,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600&q=80',
    category: 'Plants',
    subcategory: 'Succulents & Cacti',
    rating: 4.7,
    numReviews: 320,
    sold: 1450,
    stock: 85,
    featured: false,
    isNew: true,
  },
  {
    name: 'Fresh Italian Sweet Basil Kitchen Herb Plant',
    description: 'Aromatic culinarily essential Genovese sweet basil plant. Perfect for fresh pesto, pastas, and garnishes.',
    brand: 'Root Bridges',
    keywords: ['basil plant', 'herbs', 'kitchen garden', 'edible plants', 'fresh herbs'],
    price: 249,
    originalPrice: 350,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600&q=80',
    category: 'Plants',
    subcategory: 'Herbs & Edibles',
    rating: 4.6,
    numReviews: 195,
    sold: 890,
    stock: 90,
    featured: false,
    isNew: false,
  },
  {
    name: 'Self-Watering Modern Planters – Set of 3',
    description: 'Smart sub-irrigation planters with water level indicators, ensuring roots receive steady moisture for weeks.',
    brand: 'TrustBasket',
    keywords: ['planters', 'pots', 'self watering pot', 'gardening', 'planters'],
    price: 799,
    originalPrice: 1099,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&q=80',
    category: 'Plants',
    subcategory: 'Planters & Pots',
    rating: 4.7,
    numReviews: 240,
    sold: 1100,
    stock: 70,
    featured: false,
    isNew: false,
  },
  {
    name: 'Peace Lily (Spathiphyllum) Flowering Plant',
    description: 'Graceful white spathe flowers rising above dark glossy foliage. Highly effective in filtering indoor toxins.',
    brand: 'Ugaoo',
    keywords: ['peace lily', 'flowering plant', 'indoor plants', 'spathiphyllum'],
    price: 449,
    originalPrice: 620,
    discount: '28% OFF',
    image: 'https://images.unsplash.com/photo-1593691509543-c55fb32e7355?w=600&q=80',
    category: 'Plants',
    subcategory: 'Indoor Plants',
    rating: 4.8,
    numReviews: 370,
    sold: 1650,
    stock: 95,
    featured: true,
    isNew: false,
  },
  {
    name: 'Zebra Haworthia Succulent in Marble Pot',
    description: 'Architectural rosette succulent with distinctive white horizontal ridges. Extremely low maintenance.',
    brand: 'Nurserylive',
    keywords: ['zebra plant', 'haworthia', 'succulent', 'indoor plant', 'tabletop'],
    price: 349,
    originalPrice: 480,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600&q=80',
    category: 'Plants',
    subcategory: 'Succulents & Cacti',
    rating: 4.6,
    numReviews: 180,
    sold: 840,
    stock: 65,
    featured: false,
    isNew: false,
  },
  {
    name: 'Dwarf Jade Bonsai Lucky Plant',
    description: 'Symbol of good luck and prosperity. Miniature thick trunk with fleshy oval jade leaves in glazed ceramic tray.',
    brand: 'Rolling Nature',
    keywords: ['jade plant', 'bonsai', 'good luck plant', 'feng shui', 'plants'],
    price: 599,
    originalPrice: 799,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=600&q=80',
    category: 'Plants',
    subcategory: 'Indoor Plants',
    rating: 4.7,
    numReviews: 290,
    sold: 1300,
    stock: 75,
    featured: false,
    isNew: true,
  },
  {
    name: 'Organic Fresh Mint (Pudina) Herb Plant',
    description: 'Fast-growing aromatic garden mint in 5-inch nursery pot. Fresh leaves for chutneys, mocktails, and tea.',
    brand: 'Root Bridges',
    keywords: ['mint plant', 'pudina', 'herbs', 'kitchen garden', 'edible plants'],
    price: 199,
    originalPrice: 280,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&q=80',
    category: 'Plants',
    subcategory: 'Herbs & Edibles',
    rating: 4.5,
    numReviews: 160,
    sold: 920,
    stock: 110,
    featured: false,
    isNew: false,
  },
  {
    name: 'Areca Palm Natural Living Room Humidifier – Large',
    description: 'Feathery arched fronds creating tropical ambiance. Excellent natural humidifier releasing moisture into dry rooms.',
    brand: 'Ugaoo',
    keywords: ['areca palm', 'palm tree', 'large indoor plant', 'living room plant'],
    price: 899,
    originalPrice: 1299,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1599685315640-9ceab2f58944?w=600&q=80',
    category: 'Plants',
    subcategory: 'Indoor Plants',
    rating: 4.8,
    numReviews: 340,
    sold: 1150,
    stock: 50,
    featured: false,
    isNew: false,
  },
  {
    name: 'Handcrafted Terracotta Clay Planters – Set of 2',
    description: 'Breathable porous natural clay planters with matching drainage saucers for healthy root aeration.',
    brand: 'TrustBasket',
    keywords: ['terracotta pot', 'clay planters', 'pots', 'gardening pots'],
    price: 549,
    originalPrice: 750,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&q=80',
    category: 'Plants',
    subcategory: 'Planters & Pots',
    rating: 4.6,
    numReviews: 210,
    sold: 780,
    stock: 60,
    featured: false,
    isNew: false,
  },
  {
    name: 'Vibrant Magenta Bougainvillea Flowering Shrub',
    description: 'Sun-loving hardy outdoor climber producing masses of papery magenta floral bracts all year round.',
    brand: 'Nurserylive',
    keywords: ['bougainvillea', 'flowering plant', 'outdoor plants', 'balcony garden'],
    price: 349,
    originalPrice: 499,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1520412099551-62b6bafeb5bb?w=600&q=80',
    category: 'Plants',
    subcategory: 'Outdoor Plants',
    rating: 4.7,
    numReviews: 175,
    sold: 640,
    stock: 70,
    featured: false,
    isNew: false,
  },
  {
    name: 'Fresh Fragrant Rosemary Herb Plant in Ceramic Pot',
    description: 'Needle-like evergreen leaves with intense pine-like aroma. Essential culinary herb for roasting and baking.',
    brand: 'Root Bridges',
    keywords: ['rosemary plant', 'herbs', 'kitchen garden', 'aromatic plants'],
    price: 299,
    originalPrice: 420,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1515586000433-45406d8e6662?w=600&q=80',
    category: 'Plants',
    subcategory: 'Herbs & Edibles',
    rating: 4.6,
    numReviews: 150,
    sold: 580,
    stock: 80,
    featured: false,
    isNew: true,
  },
  {
    name: 'Golden Barrel Cactus in Glazed Ceramic Bowl',
    description: 'Globe-shaped ribbed cactus adorned with bright golden spines. Thrives on full sun and minimal watering.',
    brand: 'Ugaoo',
    keywords: ['cactus', 'golden barrel', 'succulents', 'desert plant', 'tabletop'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600&q=80',
    category: 'Plants',
    subcategory: 'Succulents & Cacti',
    rating: 4.8,
    numReviews: 220,
    sold: 790,
    stock: 55,
    featured: false,
    isNew: false,
  },
  {
    name: 'Arabian Jasmine (Mogra) Fragrant Plant',
    description: 'Intensely fragrant white star-shaped blooms revered for tea, aromatherapy, and Indian household gardens.',
    brand: 'Nurserylive',
    keywords: ['jasmine', 'mogra', 'fragrant plant', 'outdoor plants', 'white flowers'],
    price: 299,
    originalPrice: 399,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1593691509543-c55fb32e7355?w=600&q=80',
    category: 'Plants',
    subcategory: 'Outdoor Plants',
    rating: 4.8,
    numReviews: 390,
    sold: 1820,
    stock: 85,
    featured: false,
    isNew: false,
  },

  // ==========================================
  // 9. BOOKS (15 Products)
  // ==========================================
  {
    name: 'Atomic Habits – James Clear',
    description: 'An easy and proven framework for improving every day. Discover tiny changes that yield remarkable results.',
    brand: 'Penguin',
    keywords: ['atomic habits', 'james clear', 'self help', 'habits', 'bestseller', 'books'],
    price: 399,
    originalPrice: 599,
    discount: '33% OFF',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80',
    category: 'Books',
    subcategory: 'Self-Help',
    rating: 4.9,
    numReviews: 820,
    sold: 5600,
    stock: 200,
    featured: true,
    isNew: false,
  },
  {
    name: 'The Psychology of Money – Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn’t about what you know, it’s about behavior.',
    brand: 'Jaico',
    keywords: ['psychology of money', 'morgan housel', 'finance', 'investing', 'non fiction'],
    price: 349,
    originalPrice: 499,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=600&q=80',
    category: 'Books',
    subcategory: 'Non-Fiction',
    rating: 4.9,
    numReviews: 690,
    sold: 4300,
    stock: 180,
    featured: true,
    isNew: false,
  },
  {
    name: 'Sapiens: A Brief History of Humankind – Yuval Noah Harari',
    description: 'Groundbreaking narrative exploring how an insignificant ape became the ruler of planet Earth.',
    brand: 'Vintage',
    keywords: ['sapiens', 'harari', 'history', 'human evolution', 'non fiction'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    category: 'Books',
    subcategory: 'Non-Fiction',
    rating: 4.8,
    numReviews: 540,
    sold: 3700,
    stock: 120,
    featured: true,
    isNew: false,
  },
  {
    name: 'The Alchemist – Paulo Coelho',
    description: 'An inspiring philosophical tale of Santiago, an Andalusian shepherd boy who journeys in search of a treasure.',
    brand: 'HarperCollins',
    keywords: ['the alchemist', 'paulo coelho', 'fiction', 'novel', 'classic literature'],
    price: 299,
    originalPrice: 399,
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80',
    category: 'Books',
    subcategory: 'Fiction',
    rating: 4.7,
    numReviews: 760,
    sold: 4900,
    stock: 160,
    featured: false,
    isNew: false,
  },
  {
    name: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    description: 'Find your purpose and stay young while growing old, inspired by the centenarians of the Okinawa island.',
    brand: 'Penguin',
    keywords: ['ikigai', 'japanese secret', 'mindfulness', 'self help', 'books'],
    price: 320,
    originalPrice: 450,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&q=80',
    category: 'Books',
    subcategory: 'Self-Help',
    rating: 4.7,
    numReviews: 480,
    sold: 3100,
    stock: 140,
    featured: false,
    isNew: false,
  },
  {
    name: 'Deep Work: Rules for Focused Success – Cal Newport',
    description: 'The definitive guide to mastering intense concentration in an increasingly distracted and fragmented world.',
    brand: 'Grand Central',
    keywords: ['deep work', 'cal newport', 'productivity', 'focus', 'self help'],
    price: 425,
    originalPrice: 599,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&q=80',
    category: 'Books',
    subcategory: 'Self-Help',
    rating: 4.8,
    numReviews: 390,
    sold: 2400,
    stock: 90,
    featured: false,
    isNew: true,
  },
  {
    name: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    description: 'Robert C. Martin’s legendary manual on writing readable, maintainable, and elegant software code.',
    brand: 'Pearson',
    keywords: ['clean code', 'programming', 'software engineering', 'computer science'],
    price: 899,
    originalPrice: 1299,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=600&q=80',
    category: 'Books',
    subcategory: 'Academic & Technical',
    rating: 4.9,
    numReviews: 420,
    sold: 2150,
    stock: 80,
    featured: true,
    isNew: false,
  },
  {
    name: 'A Game of Thrones: A Song of Ice and Fire – George R.R. Martin',
    description: 'The monumental epic fantasy saga of dynastic rivalry, noble houses, ancient magic, and the Iron Throne.',
    brand: 'Bantam',
    keywords: ['game of thrones', 'fantasy', 'fiction', 'novel', 'epic saga'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&q=80',
    category: 'Books',
    subcategory: 'Fiction',
    rating: 4.8,
    numReviews: 590,
    sold: 3400,
    stock: 110,
    featured: false,
    isNew: false,
  },
  {
    name: 'The Very Hungry Caterpillar – Board Book',
    description: 'Eric Carle’s world-famous vividly illustrated classic children storybook featuring the little caterpillar.',
    brand: 'Puffin',
    keywords: ['children book', 'kids', 'picture book', 'board book', 'eric carle'],
    price: 260,
    originalPrice: 350,
    discount: '26% OFF',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    category: 'Books',
    subcategory: "Children's",
    rating: 4.9,
    numReviews: 450,
    sold: 3100,
    stock: 130,
    featured: false,
    isNew: false,
  },
  {
    name: 'Designing Data-Intensive Applications – Martin Kleppmann',
    description: 'The big ideas behind reliable, scalable, and maintainable systems: storage engines, replication, and distributed data.',
    brand: "O'Reilly",
    keywords: ['data engineering', 'system design', 'architecture', 'technical book'],
    price: 1199,
    originalPrice: 1699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=600&q=80',
    category: 'Books',
    subcategory: 'Academic & Technical',
    rating: 4.9,
    numReviews: 380,
    sold: 1750,
    stock: 65,
    featured: false,
    isNew: true,
  },
  {
    name: 'Rich Dad Poor Dad – Robert T. Kiyosaki',
    description: 'What the rich teach their kids about money that the poor and middle class do not. Financial education classic.',
    brand: 'Plata Publishing',
    keywords: ['rich dad poor dad', 'finance', 'wealth', 'investing', 'self help'],
    price: 350,
    originalPrice: 499,
    discount: '30% OFF',
    image: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=600&q=80',
    category: 'Books',
    subcategory: 'Self-Help',
    rating: 4.7,
    numReviews: 680,
    sold: 4800,
    stock: 190,
    featured: false,
    isNew: false,
  },
  {
    name: 'The Midnight Library – Matt Haig',
    description: 'Between life and death there is a library containing books of infinite lives you could have lived.',
    brand: 'Viking',
    keywords: ['midnight library', 'matt haig', 'fiction', 'novel', 'magical realism'],
    price: 399,
    originalPrice: 550,
    discount: '27% OFF',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80',
    category: 'Books',
    subcategory: 'Fiction',
    rating: 4.8,
    numReviews: 410,
    sold: 2600,
    stock: 120,
    featured: false,
    isNew: false,
  },
  {
    name: "Harry Potter and the Sorcerer's Stone – Illustrated Edition",
    description: 'J.K. Rowling’s magical journey into Hogwarts fully illustrated with breathtaking full-color artwork by Jim Kay.',
    brand: 'Bloomsbury',
    keywords: ['harry potter', 'jk rowling', 'illustrated', 'children book', 'fantasy'],
    price: 799,
    originalPrice: 1199,
    discount: '33% OFF',
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&q=80',
    category: 'Books',
    subcategory: "Children's",
    rating: 4.9,
    numReviews: 610,
    sold: 3900,
    stock: 100,
    featured: true,
    isNew: false,
  },
  {
    name: 'Thinking, Fast and Slow – Daniel Kahneman',
    description: 'Nobel laureate Daniel Kahneman takes us on a tour of the two systems that drive the way we think and decide.',
    brand: 'Farrar, Straus and Giroux',
    keywords: ['thinking fast and slow', 'psychology', 'behavioral economics', 'non fiction'],
    price: 499,
    originalPrice: 699,
    discount: '29% OFF',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    category: 'Books',
    subcategory: 'Non-Fiction',
    rating: 4.7,
    numReviews: 360,
    sold: 2100,
    stock: 85,
    featured: false,
    isNew: false,
  },
  {
    name: 'Cracking the Coding Interview (189 Programming Questions)',
    description: 'Gayle Laakmann McDowell’s industry gold standard guide to passing top tech software engineer interviews.',
    brand: 'CareerCup',
    keywords: ['coding interview', 'algorithms', 'data structures', 'programming', 'technical'],
    price: 899,
    originalPrice: 1299,
    discount: '31% OFF',
    image: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=600&q=80',
    category: 'Books',
    subcategory: 'Academic & Technical',
    rating: 4.9,
    numReviews: 470,
    sold: 2900,
    stock: 95,
    featured: false,
    isNew: false,
  },
];

async function seedAll() {
  try {
    console.log('Connecting to MongoDB Atlas...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB Atlas');

    // Count by category
    const catCounts = {};
    productsData.forEach((p) => {
      catCounts[p.category] = (catCounts[p.category] || 0) + 1;
      p.images = [p.image];
    });

    console.log('Categories to insert (must be max 15 each):', catCounts);

    // Clear and insert
    await Product.deleteMany({});
    console.log('🗑️  Cleared old products collection');

    const inserted = await Product.insertMany(productsData);
    console.log(`🎉 Successfully seeded ${inserted.length} products to MongoDB!`);

    // Verify categories in DB
    const countsInDB = {};
    for (const doc of inserted) {
      countsInDB[doc.category] = (countsInDB[doc.category] || 0) + 1;
    }
    console.log('Final product count per category in DB:', countsInDB);

    // Also update frontend fallback products file
    const frontendProductsPath = path.resolve(__dirname, '../../frontend/src/data/products.js');
    const frontendData = inserted.map((doc, idx) => ({
      _id: doc._id.toString(),
      id: doc._id.toString(),
      name: doc.name,
      price: doc.price,
      originalPrice: doc.originalPrice,
      rating: doc.rating,
      sold: doc.sold,
      stock: doc.stock,
      discount: doc.discount,
      image: doc.image,
      images: doc.images,
      category: doc.category,
      subcategory: doc.subcategory,
      brand: doc.brand,
      keywords: doc.keywords,
      description: doc.description,
      featured: doc.featured,
      isNew: doc.isNew,
    }));

    const fileContent = `// Auto-generated synchronized product catalog
export const products = ${JSON.stringify(frontendData, null, 2)};

export default products;
`;

    fs.writeFileSync(frontendProductsPath, fileContent, 'utf8');
    console.log(`✅ Updated frontend fallback catalog at ${frontendProductsPath} with ${frontendData.length} products!`);

    await mongoose.disconnect();
    console.log('✅ Disconnected from DB.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Error during seeding:', err);
    process.exit(1);
  }
}

seedAll();
